name: Build and Release EXE

on:
  push:
    branches: [ "main", "master" ] # 每次推送到主分支都会触发
    tags:
      - 'v*'                     # 打版本号标签时也会触发
  workflow_dispatch:             # 👑 关键：允许你在 GitHub 网页上直接点按钮运行！

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6 PyQt6-WebEngine requests playwright

      - name: Package to EXE
        run: |
          pyinstaller --noconsole --onefile --name "Subtitled-video-Pro" --collect-all playwright main.py

      - name: Attest EXE
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'dist/Subtitled-video-Pro.exe'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        # 当只有 push branch 触发，没有 tag 时，依然会自动创建一个 Release 来存放 EXE
        with:
          files: dist/Subtitled-video-Pro.exe
          generate_release_notes: true
